name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  libvmi:
    runs-on: ubuntu-latest

    steps:
      - name: install LibVMI dependencies
        run: sudo apt-get install -y libjson-c-dev libxen-dev
        
      - name: download microvmi Debian package
        run: |
          curl -s https://api.github.com/repos/Wenzel/libmicrovmi/releases/latest \
            | jq -r '.assets[].browser_download_url' \
            | grep -E '*.deb' \
            | wget -qi - -O microvmi.deb

      - name: install microvmi
        run: sudo dpkg -i microvmi.deb

      - name: clone LibVMI
        uses: actions/checkout@v2

      - name: configure LibVMI
        run: cmake -B_build -DENABLE_BAREFLANK=OFF .

      - name: build LibVMI
        run: make
        working-directory: _build

      - name: install LibVMI
        run: sudo make install
        working-directory: _build

